import type { Metadata } from "next";
import "./globals.css";
import Head from "next/head";
import Layout from "@/components/Layout/Layout";

export const metadata: Metadata = {
  title: "Hanks Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Next Flix</title>
      </Head>
      <body style={{backgroundColor: "#141414", }}>
        <Layout>
          {children}
        </Layout>
      </body>
    </html>
  );
}
